export const PLATFORM_LOGO = {
  gfg: "/gfg.png",
  code_evaluator: "/code_evaluator.png",
  hacker_rank: "/hacker_rank.png",
  leetcode: "/leetcode.png",
};

export const QUESTIONS_LIST = [
  {
    module: "Arrays",
    problems: [
      {
        id: 1,
        title: "Reverse an Array",
        article_link: "",
        youtube_link: "https://youtu.be/qtdEmidBdUo?si=Gds5CtcHGSBBpVeD&t=17",
        practice_link: "",
        status: false,
        // platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Rotate an Array by 'd' Places",
        article_link: "",
        youtube_link: "https://youtu.be/qtdEmidBdUo?si=8l0KcPGEz7vq1Yga&t=1618",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Generate all Subarrays from an Given Array",
        article_link: "",
        youtube_link: "https://youtu.be/s4ELTNmclKU?si=RcI-lBuwAyTp1vD2&t=21",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Search in an Unsorted Array",
        article_link: "",
        youtube_link: "https://youtu.be/s4ELTNmclKU?si=HVD6qJcqxa3ul8n7&t=393",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Find Maximum and Minimum Element",
        article_link: "",
        youtube_link: "https://youtu.be/V21A4WXXmO0?si=kAMRqub1u32TyukY&t=21",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 5,
        title: "K'th Smallest/Largest Element in an Unsorted Array",
        article_link: "",
        youtube_link: "https://youtu.be/V21A4WXXmO0?si=CT5s2TzQ1YOygm1i&t=714",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 6,
        title: "Search in an Unsorted Array",
        article_link: "",
        youtube_link: "https://youtu.be/s4ELTNmclKU?si=HVD6qJcqxa3ul8n7&t=393",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 7,
        title: "Two Sum",
        article_link: "",
        youtube_link: "https://youtu.be/cSWigzTZKUs?si=Mjx033ETNO_D4ndD&t=18",
        practice_link: "https://leetcode.com/problems/two-sum/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 7,
        title: "Contains Duplicate",
        article_link: "",
        youtube_link: "https://youtu.be/cSWigzTZKUs?si=uQsP8XcI9f6cRH3s&t=540",
        practice_link:
          "https://leetcode.com/problems/contains-duplicate/description/",
        status: false,
        platform: "leetcode",
      },
    ],
  },
  {
    module: "2D Arrays",
    problems: [
      {
        id: 1,
        title: "Introduction to Two-Dimensional (2D) Arrays",
        article_link: "",
        youtube_link: "https://youtu.be/Qb34oLeSyGQ?si=2dwHHqdMCTSlK1YO&t=13",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Sums of Diagonals",
        article_link: "",
        youtube_link: "https://youtu.be/Qb34oLeSyGQ?si=a4gBmCMRcV5cynGa&t=730",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Transpose of a Matrix",
        article_link: "",
        youtube_link: "https://youtu.be/rbceUhPtu6Q?si=kogUGuWiAYeQ8gyd&t=16",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Rotate Matrix Clockwise",
        article_link: "",
        youtube_link: "https://youtu.be/rbceUhPtu6Q?si=2nK467SlLUs9BS8l&t=1207",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 5,
        title: "Print Matrix in Snake Pattern",
        article_link: "",
        youtube_link: "https://youtu.be/9S2ruGh_Pic?si=GlqzJFGL9TEIVshM&t=16",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 6,
        title: "Spiral Traversal of Matrix",
        article_link: "",
        youtube_link: "https://youtu.be/9yAH-9pJ8Ys?si=VkTqqTEFXQCxv-xw&t=16",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Strings",
    problems: [
      {
        id: 1,
        title: "Introduction to Strings",
        article_link: "",
        youtube_link: "https://youtu.be/mgXCqvtyj14?si=4DtzOBI4MPuc1dX7&t=14",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Find all Substrings",
        article_link: "",
        youtube_link: "https://youtu.be/Zql2mpwsCFk?si=3doHRqROmDDn4725&t=19",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Reverse a String",
        article_link: "",
        youtube_link: "https://youtu.be/Zql2mpwsCFk?si=VFfd-JLlayU9c20J&t=397",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Palindrome or Not",
        article_link: "",
        youtube_link: "https://youtu.be/YIRIrjqFz5M?si=DGjuDr18qPBWk9Tu&t=16",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 5,
        title: "Palindromic Substrings",
        article_link: "",
        youtube_link: "https://youtu.be/YIRIrjqFz5M?si=adBHX3pvos2uzu-z&t=708",
        practice_link:
          "https://leetcode.com/problems/palindromic-substrings/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 6,
        title: "Remove All Occurrences Of A Character In A String",
        article_link: "",
        youtube_link: "https://youtu.be/M9XWMZpPFIA?si=l_DXuWAtALaYMDHE&t=23",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 6,
        title: "Camel Case Of A Given Sentence",
        article_link: "",
        youtube_link: "https://youtu.be/M9XWMZpPFIA?si=XaPW7r1UQkfuQ6Fl&t=598",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Sets",
    problems: [
      {
        id: 1,
        title: "Introduction to Sets",
        article_link: "",
        youtube_link: "https://youtu.be/JyXh0JkJlUY?si=csEK9c_biHRDre-h&t=15",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/kPoNk6x2fjk?si=EDv-ceqFNufwV32k&t=29",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Number of Vowels in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/kPoNk6x2fjk?si=JU7ITUTcw7At0wI4&t=304",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Pangram or Not",
        article_link: "",
        youtube_link: "https://youtu.be/kPoNk6x2fjk?si=CBvb8ugoMx9wj2-L&t=1013",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Dictionaries",
    problems: [
      {
        id: 1,
        title: "Introduction to Dictionary",
        article_link: "",
        youtube_link: "https://youtu.be/ops0bm1XzNk?si=f1ijRbK1H1h95AWl",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=IlvuIm1T-Bp9t5vT&t=30",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Frequency of Each Character in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/kPoNk6x2fjk?si=JU7ITUTcw7At0wI4&t=304",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Find All Duplicate Characters in String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=fiRpF3oKKxmW2FTv&t=887",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Palindrome Permutation",
        article_link: "",
        youtube_link: "https://youtu.be/kPEBV0RsabI?si=Q0xkeivEO0B3wSQ5&t=18",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Valid Anagram",
        article_link: "",
        youtube_link: "https://youtu.be/kPEBV0RsabI?si=pfUQr7__AKerfaoQ&t=821",
        practice_link:
          "https://leetcode.com/problems/valid-anagram/description/",
        status: false,
        platform: "leetcode",
      },
    ],
  },
  {
    module: "Two Pointers",
    problems: [
      {
        id: 1,
        title: "Introduction to Two Pointers Technique",
        article_link: "",
        youtube_link: "https://youtu.be/6fqAyHoYxa4?si=ipRkZncze6leik3I&t=9",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Palindrome or Not",
        article_link: "",
        youtube_link: "https://youtu.be/6fqAyHoYxa4?si=OZQx2p1mOWfV4X14&t=604",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Two Sum II",
        article_link: "",
        youtube_link: "https://youtu.be/6fqAyHoYxa4?si=Oy7GkxyOTsAfSXND&t=1161",
        practice_link:
          "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 4,
        title: "Remove Duplicates From Sorted Array",
        article_link: "",
        youtube_link: "https://youtu.be/7wf914gwCpM?si=GCnt7Gd__lqv1Wrb&t=14",
        practice_link:
          "https://leetcode.com/problems/remove-duplicates-from-sorted-array/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 4,
        title: "Boats To Save People",
        article_link: "",
        youtube_link: "https://youtu.be/tPekWXwNFmo?si=RD0STPzCGWoCPJZd&t=12",
        practice_link:
          "https://leetcode.com/problems/boats-to-save-people/description/",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Sliding Window",
    problems: [
      {
        id: 1,
        title: "Introduction to Dictionary",
        article_link: "",
        youtube_link: "https://youtu.be/ops0bm1XzNk?si=f1ijRbK1H1h95AWl",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=IlvuIm1T-Bp9t5vT&t=30",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Searching",
    problems: [
      {
        id: 1,
        title: "Introduction to Dictionary",
        article_link: "",
        youtube_link: "https://youtu.be/ops0bm1XzNk?si=f1ijRbK1H1h95AWl",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=IlvuIm1T-Bp9t5vT&t=30",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Sorting",
    problems: [
      {
        id: 1,
        title: "Introduction to Dictionary",
        article_link: "",
        youtube_link: "https://youtu.be/ops0bm1XzNk?si=f1ijRbK1H1h95AWl",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=IlvuIm1T-Bp9t5vT&t=30",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Bit Manipulation",
    problems: [
      {
        id: 1,
        title: "Introduction to Dictionary",
        article_link: "",
        youtube_link: "https://youtu.be/ops0bm1XzNk?si=f1ijRbK1H1h95AWl",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=IlvuIm1T-Bp9t5vT&t=30",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
];

export const A2Z_QUESTIONS_LIST = [
  {
    module: "Arrays",
    problems: [
      {
        id: 1,
        title: "Remove Duplicates from Sorted Array",
        article_link: "",
        youtube_link: "",
        practice_link:
          "https://leetcode.com/problems/remove-duplicates-from-sorted-array/description/",
        difficulty: "easy",
        status: false,
        platform: "leetcode",
      },
      {
        id: 2,
        title: "Move Zeroes",
        article_link: "",
        youtube_link: "",
        practice_link: "https://leetcode.com/problems/move-zeroes/description/",
        difficulty: "easy",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Union of Two Arrays",
        article_link: "",
        youtube_link: "",
        practice_link:
          "https://www.geeksforgeeks.org/problems/union-of-two-arrays3538/1",
        difficulty: "easy",
        status: false,
        platform: "gfg",
      },
      {
        id: 4,
        title: "Max Consecutive Ones",
        article_link: "",
        youtube_link: "",
        difficulty: "easy",
        practice_link:
          "https://leetcode.com/problems/max-consecutive-ones/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 5,
        title: "Missing Number",
        article_link: "",
        youtube_link: "",
        difficulty: "easy",
        practice_link:
          "https://leetcode.com/problems/missing-number/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 6,
        title: "Rotate Array",
        article_link: "",
        youtube_link: "",
        difficulty: "medium",
        practice_link:
          "https://leetcode.com/problems/rotate-array/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Longest Sub-Array with Sum K",
        article_link: "",
        youtube_link: "",
        difficulty: "medium",
        practice_link:
          "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1",
        status: false,
        platform: "gfg",
      },
      {
        id: 3,
        title: "Max Consecutive Ones",
        article_link: "",
        youtube_link: "",
        difficulty: "easy",
        practice_link:
          "https://leetcode.com/problems/max-consecutive-ones/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Two Sum",
        article_link: "",
        youtube_link: "",
        difficulty: "easy",
        practice_link: "https://leetcode.com/problems/two-sum/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Sort Colors",
        article_link: "",
        youtube_link: "",
        difficulty: "medium",
        practice_link: "https://leetcode.com/problems/sort-colors",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Maximum Subarray Sum (Kadane's Algorithm)",
        article_link: "",
        youtube_link: "",
        difficulty: "medium",
        practice_link:
          "https://leetcode.com/problems/maximum-subarray/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Best Time to Buy and Sell Stock",
        article_link: "",
        youtube_link: "",
        difficulty: "easy",
        practice_link:
          "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Replace Elements with Greatest Element on Right Side",
        article_link: "",
        youtube_link: "",
        difficulty: "easy",
        practice_link:
          "https://leetcode.com/problems/replace-elements-with-greatest-element-on-right-side/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Set Matrix Zeroes",
        article_link: "",
        youtube_link: "",
        difficulty: "medium",
        practice_link:
          "https://leetcode.com/problems/set-matrix-zeroes/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Rotate Image",
        article_link: "",
        youtube_link: "",
        difficulty: "medium",
        practice_link:
          "https://leetcode.com/problems/rotate-image/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Spiral Matrix",
        article_link: "",
        youtube_link: "",
        difficulty: "medium",
        practice_link:
          "https://leetcode.com/problems/spiral-matrix/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Pascal's Triangle",
        article_link: "",
        youtube_link: "",
        difficulty: "easy",
        practice_link:
          "https://leetcode.com/problems/pascals-triangle/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "3 Sum",
        article_link: "",
        youtube_link: "",
        difficulty: "medium",
        practice_link: "https://leetcode.com/problems/3sum/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 3,
        title: "Merge Intervals",
        article_link: "",
        youtube_link: "",
        difficulty: "medium",
        practice_link:
          "https://leetcode.com/problems/merge-intervals/description/",
        status: false,
        platform: "leetcode",
      },
    ],
  },

  {
    module: "Strings",
    problems: [
      {
        id: 1,
        title: "Introduction to Strings",
        article_link: "",
        youtube_link: "https://youtu.be/mgXCqvtyj14?si=4DtzOBI4MPuc1dX7&t=14",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Find all Substrings",
        article_link: "",
        youtube_link: "https://youtu.be/Zql2mpwsCFk?si=3doHRqROmDDn4725&t=19",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Reverse a String",
        article_link: "",
        youtube_link: "https://youtu.be/Zql2mpwsCFk?si=VFfd-JLlayU9c20J&t=397",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Palindrome or Not",
        article_link: "",
        youtube_link: "https://youtu.be/YIRIrjqFz5M?si=DGjuDr18qPBWk9Tu&t=16",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 5,
        title: "Palindromic Substrings",
        article_link: "",
        youtube_link: "https://youtu.be/YIRIrjqFz5M?si=adBHX3pvos2uzu-z&t=708",
        practice_link:
          "https://leetcode.com/problems/palindromic-substrings/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 6,
        title: "Remove All Occurrences Of A Character In A String",
        article_link: "",
        youtube_link: "https://youtu.be/M9XWMZpPFIA?si=l_DXuWAtALaYMDHE&t=23",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 6,
        title: "Camel Case Of A Given Sentence",
        article_link: "",
        youtube_link: "https://youtu.be/M9XWMZpPFIA?si=XaPW7r1UQkfuQ6Fl&t=598",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Sets",
    problems: [
      {
        id: 1,
        title: "Introduction to Sets",
        article_link: "",
        youtube_link: "https://youtu.be/JyXh0JkJlUY?si=csEK9c_biHRDre-h&t=15",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/kPoNk6x2fjk?si=EDv-ceqFNufwV32k&t=29",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Number of Vowels in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/kPoNk6x2fjk?si=JU7ITUTcw7At0wI4&t=304",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Pangram or Not",
        article_link: "",
        youtube_link: "https://youtu.be/kPoNk6x2fjk?si=CBvb8ugoMx9wj2-L&t=1013",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Dictionaries",
    problems: [
      {
        id: 1,
        title: "Introduction to Dictionary",
        article_link: "",
        youtube_link: "https://youtu.be/ops0bm1XzNk?si=f1ijRbK1H1h95AWl",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=IlvuIm1T-Bp9t5vT&t=30",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Frequency of Each Character in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/kPoNk6x2fjk?si=JU7ITUTcw7At0wI4&t=304",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Find All Duplicate Characters in String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=fiRpF3oKKxmW2FTv&t=887",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Palindrome Permutation",
        article_link: "",
        youtube_link: "https://youtu.be/kPEBV0RsabI?si=Q0xkeivEO0B3wSQ5&t=18",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 4,
        title: "Valid Anagram",
        article_link: "",
        youtube_link: "https://youtu.be/kPEBV0RsabI?si=pfUQr7__AKerfaoQ&t=821",
        practice_link:
          "https://leetcode.com/problems/valid-anagram/description/",
        status: false,
        platform: "leetcode",
      },
    ],
  },
  {
    module: "Two Pointers",
    problems: [
      {
        id: 1,
        title: "Introduction to Two Pointers Technique",
        article_link: "",
        youtube_link: "https://youtu.be/6fqAyHoYxa4?si=ipRkZncze6leik3I&t=9",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Palindrome or Not",
        article_link: "",
        youtube_link: "https://youtu.be/6fqAyHoYxa4?si=OZQx2p1mOWfV4X14&t=604",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 3,
        title: "Two Sum II",
        article_link: "",
        youtube_link: "https://youtu.be/6fqAyHoYxa4?si=Oy7GkxyOTsAfSXND&t=1161",
        practice_link:
          "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 4,
        title: "Remove Duplicates From Sorted Array",
        article_link: "",
        youtube_link: "https://youtu.be/7wf914gwCpM?si=GCnt7Gd__lqv1Wrb&t=14",
        practice_link:
          "https://leetcode.com/problems/remove-duplicates-from-sorted-array/description/",
        status: false,
        platform: "leetcode",
      },
      {
        id: 4,
        title: "Boats To Save People",
        article_link: "",
        youtube_link: "https://youtu.be/tPekWXwNFmo?si=RD0STPzCGWoCPJZd&t=12",
        practice_link:
          "https://leetcode.com/problems/boats-to-save-people/description/",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Sliding Window",
    problems: [
      {
        id: 1,
        title: "Introduction to Dictionary",
        article_link: "",
        youtube_link: "https://youtu.be/ops0bm1XzNk?si=f1ijRbK1H1h95AWl",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=IlvuIm1T-Bp9t5vT&t=30",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Searching",
    problems: [
      {
        id: 1,
        title: "Introduction to Dictionary",
        article_link: "",
        youtube_link: "https://youtu.be/ops0bm1XzNk?si=f1ijRbK1H1h95AWl",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=IlvuIm1T-Bp9t5vT&t=30",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Sorting",
    problems: [
      {
        id: 1,
        title: "Introduction to Dictionary",
        article_link: "",
        youtube_link: "https://youtu.be/ops0bm1XzNk?si=f1ijRbK1H1h95AWl",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=IlvuIm1T-Bp9t5vT&t=30",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
  {
    module: "Bit Manipulation",
    problems: [
      {
        id: 1,
        title: "Introduction to Dictionary",
        article_link: "",
        youtube_link: "https://youtu.be/ops0bm1XzNk?si=f1ijRbK1H1h95AWl",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
      {
        id: 2,
        title: "Number of Unique Characters in a Given String",
        article_link: "",
        youtube_link: "https://youtu.be/Kx6QTrjIwaw?si=IlvuIm1T-Bp9t5vT&t=30",
        practice_link: "",
        status: false,
        platform: "code_evaluator",
      },
    ],
  },
];
